- README.md
- Adventures in Angular
- Javascript Jabber
- Hanselminutes
- NodeUp
> Adding some very good podcasts

- README.md
> add new podecast in english

- README.md
> add TTL Podcast

- README.md
> add CocoaHeadsBR Podcast

- README.md
Add Podcast discussing development, design, and the business of great products.
> Add Giant Robots PodcCast

- README.md
Corrigi os links do iTunes, e também adicionei o site correto da comunidade.
> Corrigido link CocoaHeadsBr

- README.md
> Added PODebug

- README.md
Podcast em inglês que fala sobre desenvolvimento para a plataforma Apple.
> Adicionado o Ray Wenderlich Podcast

- README.md
Your work is really cool and i decided to contribute with it (:
> Added some podcasts (:

- README.md
O Startapo discute temas, conceitos, cases, novidades, polêmicas e tudo o que envolve o universo da tecnologia, empreendedorismo, e das startups. Novos programas são lançados quinzenalmente.
> Startapo adicionado

- README.md
[Fontes](https://twitter.com/zofepod/status/712705163346182144)
> correção do fim do zofe

- README.md
Capycast é o podcast do time de desenvolvedores da Resultados Digitais.
> adding capycast

- README.md
Podcast da área de tecnologia e segurança da informação
> Adição do podcast SegInfocast

- README.md
Adicionado o Happy Hour Podecast do 9to5Mac
> Added happy hour podcast from 9to5Mac on the list

- README.md
Br  - Loop Matinal 
En - Android  Intelligence,  XDA Developers
> +3 Poscasts

- README.md
O ultimo do [Front In Cuiabá](https://codetalks.net/front-in-cuiab%C3%A1-e-como-construir-um-ecossistema-piruleta-221511251386#.prkamekww)
> ta de volta o codetalk

- README.md
> Adicionado MonkeyNights.

- README.md
Hey I added 3 new podcasts
Frontend Happy Hour - It's an amazing podcast about frontend where they drink everytime someone says an special word of the day.
Motion and Meaning - A podcast about motion for digital designers, but it's very interesting to devs also.
SVG Immersion - all you need to know about the future of svg
> Add new podcasts

- README.md
Adicionado mais um podcast BR, 5 podcasts em inglês e corrigindo a url da playlist do CapyCast no SoundCloud,
> Adicionando +6 Podcasts

- README.md
Além da adição de novos podcasts, foi feito uma pequena modificação quanto à ordem alfabética de um podcast já existente.
> Adição de novos podcasts

- README.md
> Adição de um podcast.

- README.md
Adiciona o OpenDevPodcast à lista
> Adiciona o OpenDevPodcast

- README.md
Adicionados:
-  Hipsters.Tech
- PodProgramar
- podcast.__init__
- The Web Plataform
- Talking Code
- Three Devs and a Maybe
> New Podcasts

- README.md
Primeira vez que to fazendo um pull request, se tiver alguma coisa errada aew só avisar. Adicionei estes 3 podcasts brazucas. Muito bom o repositório!
> Adicionado 3 podcasts - Lambda3/ Dev & Community/ Codecasts

- data/podcasts.json
Adicionando descrição para o PodCast.
> Atualização de informações do ShipIt

- data/podcasts.json
> Add RSS for Shipit!

- data/podcasts.json
Adicionado bluesoft podcast na listagem
> adicionado bluesoft podcast

- data/podcasts.json
Podcast focado em Metodologias Ágeis.
> Add Meta-Cast, an agile podcast

- data/podcasts.json
> add field image to podcast no have twitter

- data/podcasts.json
Através de uma [publicação](https://github.com/training-center/forum/issues/71), no forum do Training Center, acabei conhecendo esse repositório. Estou adicionando novos podcasts pra lista :)
> Adding podcasts: Lovelace Cast, Papo Livre, HTTP 203, freeCodeCamp.

- data/podcasts.json
> Adição do Podcast 10deploys

- data/podcasts.json
Those are two great podcasts from @jamesmontemagno
> Add Merge Conflict and Xamarin Podcast

- data/podcasts.json
> Add podTag podcast

- data/podcasts.json
> Updating informations of podcast QuebraDev

- data/podcasts.json
Adding https://podentender.com to the list
> Adding PODEntender to the list
